---
- name: Add multiple users belongs to differnt groups
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Add users
      user:
        name: "{{ item.name }}"
        state: present
        groups: "{{ item.groups }}"
      loop:
        - { name: 'user1', groups: 'wheel' }
        - { name: 'user2', groups: 'root' }

