---
- name: create a directory and copy a file to remote hosts
  hosts: all
  become: yes
  become_user: root
  vars:
    remote_dir: /tmp/example
    sample_file: /tmp/sample.txt

  tasks:
    - name: Create a directory on remote host
      file:
        path: "{{ remote_dir }}"
        state: directory
        recurse: true

    - name: copy a file from ansible master to remote directory
      copy:
        src: "{{ sample_file }}"
        dest: "{{ remote_dir }}"
