---
- name: Install packages
  hosts: all
  become: true
  become_user: root
  vars:
    required_packages:
      - epel-release
      - redis
      - httpd

  tasks:
    - name: Install http and redis packages
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ required_packages }}"

