---
- name: Install packages
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Install http and redis packages
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - epel-release
        - redis
        - httpd

